#+TITLE: A formula sheet for University of Waterloo/Guelph Phys 701/7010, Quantum Mechanics I 
#+AUTHOR: Jim Martin /et al./
#+DATE: 

* Rendered version:
- a pdf rendering is at: https://v2.overleaf.com/read/rvjgqzcjkxyx

* Notes on contributing:
Please let me know of any corrections.  I am open to suggestions for additions, subject to the following guidelines:
- I will not consider suggestions made less than one week before final exam.  There is too much potential for ``last-minute'' mistakes to arise.
- my preference is to receive suggestions as github pull requests, but e-mail is acceptable.
- if you send e-mail, please provide latex code.  [[http://www.overleaf.com]] is a good way to check your code online.
- please provide a reference for your suggestion (I'll be working on inserting more references into latex source code).
- I use lualatex to compile (see Makefile).  This will be irrelevant for most contributions, unless you wish to make use of some of lualatex's features.

* Note on sources:
- the table of constants is adapted from: [[http://johanw.home.xs4all.nl/contents.html]]

